- public/plantilla/js/manejadorGuias.js
- public/plantilla/js/render.js
prettier, actualización control de accesos, actualización, mostrar tipo de envio en la interfaz!
> tip de entrega uploaded

- public/plantilla/admin.html
> Frecuent items2

- .vscode/settings.json
- public/plantilla/js/cargadorDeDatos.js
al presionar el ok del modal, te mueve a bodegas, si solo lo borras te deja en el cotizador
> No storehouse notification

- public/plantilla/admin.html
- public/plantilla/js/callcenter/callcenter.js
- public/plantilla/js/cargadorDeDatos.js
- public/plantilla/js/chargeusers.js
- public/plantilla/js/render.js
Seller list on startup
better retroalimentation in callcenter queries
Solve problem on modal solving in callcenter
> New callcenter

- public/plantilla/js/cotizador.js
pls review! importante feature
> servi office block inputs

- public/plantilla/admin.html
- public/plantilla/js/cargadorDeDatos.js
- public/plantilla/js/usuarios.js
- public/plantilla/plataforma2.html
> Referidos 2

- public/plantilla/admin.html
- public/plantilla/js/buscarUsuarios.js
- public/plantilla/js/cargadorDeDatos.js
- public/plantilla/js/chargeusers.js
> Table users admin

- public/plantilla/admin.html
- public/plantilla/js/manejadorGuias.js
- public/plantilla/js/usuarios.js
just check admin.html n' usuarios.js !
Estadiscticas globales funcionando!
> Global stats

- public/plantilla/admin.html
- public/plantilla/js/manejadorGuias.js
- public/plantilla/js/usuarios.js
- public/plantilla/plataforma2.html
creación de notificaciones desde el admin para la activación de bodegas!
> Warehouse notification

- public/plantilla/js/cotizador/plantillas.js
Solución al problema de las plantillas en el cotizador
> Plantillas cuidad

- public/plantilla/admin.html
- public/plantilla/js/usuarios.js
- public/plantilla/plataforma2.html
código de las bodegas eliminado del código!
> Remove warehouses

- public/plantilla/js/callcenter/callcenter.js
Edit regular expresion to solve callcenter error
> solve call center error

- public/plantilla/admin.html
- public/plantilla/js/recolecciones/index.js
Nueva tabla! no consume todos los nodos del dom del documento en html :
> Inter recolections table

- public/plantilla/admin.html
- public/plantilla/js/usuarios.js
Funcionalidad para ver la fehca y hora de registro en el panel de revisión individual del usuario
> Date on user

- public/plantilla/js/cotizador.js
Reputación de transportadoras en el cotizador!
> Trans reputation

- public/plantilla/js/cotizador.js
- public/plantilla/js/cotizador/cotizadorApi.js
- public/plantilla/js/cotizador/views.js
- public/plantilla/js/recolecciones/index.js
Todas las funciones de escritura de nodos en el DOM ahora son sincrónicas, lo que implica que no puedo realizar consultas (queries) dentro de ellas. Para resolver esto, tendríamos que hacer que esas funciones fueran asíncronas, lo cual no tendría sentido en este contexto.
Por lo tanto, decidí subir la lógica de la consulta al nivel principal. Antes de comenzar los métodos de impresión, se ejecuta un método de agregación de la información del cotizador.
En la función asíncrona cotizadorApi, justo después de recibir la respuesta de la plataforma 2, utilizo un metodo que realiza una consulta a la función fetchEstadisticas, la cual recibe la transportadora y el destino como parámetros, y devuelve el porcentaje correspondiente.
Ya con el valor de reputación dentro de los objetos …
> New quoter - reputación transportadoras!

- public/plantilla/js/cargadorDeDatos.js
- public/plantilla/js/cotizador.js
- public/plantilla/js/cotizador/cotizadorApi.js
funcionamiento adecuado de las plantillas en el cotizador conectado con la P2!!!
> Template quoter

- public/plantilla/admin.html
- public/plantilla/js/manejadorGuias.js
Menú de acciones en el panel del admin! Este rol ya no tendrá que ingresar al usuario individual para realizar las acciones de:
- Descargar guías
- Regenerar guías
Modificación al menú de modificación de datos bancarios, para que no reciba tipos de documento no permitidos!
> Actions guides

- public/plantilla/js/cotizador.js
Muevo la lógica de creación de usuarios frecuentes y objetos mas lejos en el entorno de ejecución!
Mando la información del dane de la ciudad sacandola del objeto datos_a_enviar para guardarla en los clientes frecuentes!
> city id on frecuent user

- public/plantilla/admin.html
- public/plantilla/js/cargadorDeDatos.js
- public/plantilla/js/usuarios.js
uso del a variable celular2 para enviar el mensaje de whatsapp para el desbloqueo de la billetera!!!
> Alternative number

- public/plantilla/js/cargadorDeDatos.js
- public/plantilla/js/manejadorGuias.js
- public/plantilla/js/notificaciones/index.js
- public/plantilla/js/render.js
nuevo excel de generación de pagos!!!
> Upgrade payment excel

- public/plantilla/js/cargadorDeDatos.js
fix-variable-localStorage-updateUserSegmentation
> fix-variable-localStorage-updateUserSegmentation

- public/plantilla/js/manejadorGuias.js
- public/plantilla/js/render.js
- public/plantilla/js/utils/viewer.js
- public/plantilla/plataforma2.html
fix-and-refactor-functions-javascript
> fix-and-refactor-functions-javascript

- public/plantilla/js/auth/handlers.js
- public/plantilla/js/auth/register.js
- public/plantilla/js/bodegas/bodegas.js
- public/plantilla/js/callcenter/callcenter.js
- public/plantilla/js/ciudades/index.js
- public/plantilla/js/config/initializeFirebase.js
- public/plantilla/js/cotizador.js
- public/plantilla/js/cotizador/cotizadorFlexii.js
- public/plantilla/js/gestionarTienda.js
- public/plantilla/js/historialGuias/historial.js
- public/plantilla/js/homeView/main.js
- public/plantilla/js/movimientoGuias/novedades.js
- public/plantilla/js/oficinas/index.js
- public/plantilla/js/pagos/comprobadores.js
- public/plantilla/js/pagos/facturacion.js
- public/plantilla/js/pagos/index.js
- public/plantilla/js/pagos/pagar.js
- public/plantilla/js/puntoEnvio/crearPedido.js
- public/plantilla/js/puntoEnvio/estadosFlexii.js
- public/plantilla/js/puntoEnvio/generadorPedidos.js
- public/plantilla/js/puntoEnvio/recibirPaquete.js
- public/plantilla/js/puntoEnvio/tablaEnvios.js
- public/plantilla/js/render.js
- public/plantilla/js/usuarios.js
- public/plantilla/js/utils/functions.js
refactor-firebase11-pagos,puntoEnvio,render,usuarios,utils
> refactor-firebase11-pagos,puntoEnvio,render,usuarios,utils

- public/plantilla/admin.html
- public/plantilla/js/cargadorDeDatos.js
- public/plantilla/js/config/initializeFirebase.js
- public/plantilla/js/cotizador.js
- public/plantilla/js/historialGuias/historial.js
- public/plantilla/js/manejadorGuias.js
- public/plantilla/js/oficinas/index.js
- public/plantilla/js/pagos/facturacion.js
- public/plantilla/js/pagos/index.js
> fixes-functions
